pageaccueil:
    path:     /
    defaults: { _controller: GSBGestionStatistiqueBundle:Default:index }

affichagestatistique:
    path:     /statistiques
    defaults: { _controller: GSBGestionStatistiqueBundle:Default:afficherStat }

affichageVisiteur:
    path:     /visiteurs
    defaults: { _controller: GSBGestionStatistiqueBundle:Default:afficherVis }
