pageaccueil:
    path:     /
    defaults: { _controller: GSBGestionStatistiqueBundle:Default:index }

affichagestatistique:
    path:     /statistiques
    defaults: { _controller: GSBGestionStatistiqueBundle:Default:afficherStat }

affichageDel:
    path:     /delegue
    defaults: { _controller: GSBGestionStatistiqueBundle:Default:afficherDel }

affichageRegions:
    path:     /regions
    defaults: { _controller: GSBGestionStatistiqueBundle:Default:afficherStatRegion }

affichageSecteur:
    path:   /secteur
    defaults: { _controller: GSBGestionStatistiqueBundle:Default:afficherStatSecteur }

affichageVisiteursRegion:
    path:     /region
    defaults: { _controller: GSBGestionStatistiqueBundle:Default:afficherVisiteursRegion }

pageConnexion:
    path:   /connexion
    defaults: { _controller: GSBGestionStatistiqueBundle:Default:pageConnexion }
