<?php

namespace GSB\GestionStatistiqueBundle\Repository;

/**
 * SecteurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SecteurRepository extends \Doctrine\ORM\EntityRepository
{
    public function getNbVisiteurs()
    {
        $repository = $this->getEntityManager()->getRepository('GSBGestionStatistiqueBundle:Secteur');
        $qb = $repository->createQueryBuilder('Secteur');
        return $qb
            ->select('s.libelleSec, COUNT(v.id) AS nbVisiteurs')
            ->from('GSBGestionStatistiqueBundle:Secteur', 's')
            ->from('GSBGestionStatistiqueBundle:Visiteur', 'v')
            ->where('s.id = v.codeSecteur')
            ->groupBy('s.libelleSec')
            ->getQuery()
            ->getResult();
    }
}
