<?php

namespace GSB\GestionStatistiqueBundle\Repository;

/**
 * TravaillerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TravaillerRepository extends \Doctrine\ORM\EntityRepository
{
    public function getNombreVisiteursDeLaRegion($idRegion)
    {
        $repository = $this->getEntityManager()->getRepository('GSBGestionStatistiqueBundle:Travailler');
        $qb = $repository->createQueryBuilder('Travailler');
        return $qb
            ->select('count(Travailler.matriculeVis)')
            ->where("Travailler.codeReg = ?1")
            ->setParameter(1, $idRegion)
            ->getQuery()
            ->getSingleScalarResult();
    }

    public function getNombreDeleguesDeLaRegion($idRegion)
    {
        $repository = $this->getEntityManager()->getRepository('GSBGestionStatistiqueBundle:Travailler');
        $qb = $repository->createQueryBuilder('Travailler');
        return $qb
            ->select('count(Travailler.matriculeVis)')
            ->where("Travailler.codeReg = ?1")
            ->andWhere("Travailler.roleTrav = 'Délégué'")
            ->setParameter(1, $idRegion)
            ->getQuery()
            ->getSingleScalarResult();
    }

    public function getVisiteursDeLaRegion($idRegion)
    {
        /*$repository = $this->getEntityManager()->getRepository('GSBGestionStatistiqueBundle:Visiteur');
        $qb = $repository->createQueryBuilder('Visiteur');
        return $qb
                    ->join('Visiteur.id', 'Travailler')
                    //->where("Travailler.codeReg = ?1")
                    //->setParameter(1, $idRegion)
                    ->getQuery()
                    ->getResult();*/

        $repository = $this->getEntityManager()->getRepository('GSBGestionStatistiqueBundle:Visiteur');
        $qb = $repository->createQueryBuilder('Visiteur');
        return $qb	->select('v')
			        ->from('GSBGestionStatistiqueBundle:Visiteur','v')
			        ->from('GSBGestionStatistiqueBundle:Travailler','t')
					->where('v.id = t.matriculeVis')
					->andWhere("t.codeReg = ?1")
                    ->setParameter(1, $idRegion)
                    ->getQuery()
                    ->getResult();

    }
}
