<?php

namespace GSB\GestionStatistiqueBundle\Repository;

/**
 * VisiteurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VisiteurRepository extends \Doctrine\ORM\EntityRepository
{
	public function getDepartement()
	{

        $repository = $this->getEntityManager()->getRepository('GSBGestionStatistiqueBundle:Visiteur');
        $qb = $repository->createQueryBuilder('Visiteur');
        return $qb	->select('v.id','v.adresseVis','v.nomVis','v.cpVis','v.villeVis','v.dateEmbauche','d.nomDep','s.libelleSec')
			        ->from('GSBGestionStatistiqueBundle:Visiteur','v')
			        ->from('GSBGestionStatistiqueBundle:Departement','d')
			        ->from('GSBGestionStatistiqueBundle:Secteur','s')
			        ->from('GSBGestionStatistiqueBundle:Travailler','t')
					->where('v.codeDep = d.id')
					->andWhere('v.codeSecteur = s.id')
					->andWhere('v.id = t.matriculeVis')
					->andWhere("t.roleTrav = 'Délégué'")
					->groupBy('v.id')
                    ->getQuery()
                    ->getResult();
	}
}
